import type { Metadata } from "next";
import localFont from "next/font/local";

// Font Awesome
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false; // 자동으로 CSS 추가하는 기능 끄기

import "../styles/globals.css";
import { AlertProvider } from "./components/alert";
import { Toaster } from "./components/toast";
import { TooltipProvider } from "@/components/ui/tooltip";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} antialiased`}>
      <body className={pretendard.className}>
        <TooltipProvider>
          <AlertProvider />
          <Toaster />
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
